In [4]:
import pandas as pd

In [5]:
from googletrans import Translator

translater = Translator()

In [6]:
df = pd.read_excel("cleaned_reviews_data.xlsx")

In [7]:
# getting 200 to 300 reviews from  the data set to avoid api blocking.

nw_df = df.loc[5701:6000,:]

In [8]:
nw_df.shape

(300, 3)

In [9]:
# Creat a new column ("reviews") that contains translated Reviews of Portuguese

def translate_to_english(text):
  
  text2 = str(text)
  trans = translater.translate(text2, dest='en')
  return trans.text

nw_df["reviews_en"] =  pd.DataFrame(nw_df["reviews"].apply(lambda x: translate_to_english(x)))

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [10]:
nw_df.head()

,order_id,review_score,reviews,reviews_en
5701,62a303159c09b65c288433ea06a99600,5,otimo produto muito bom gostei muito veio td c...,great product very good I liked it very much c...
5702,e8608de908926d0a19ad92ae1af61175,5,recebi o produto recomendo a loja,I received the product I recommend the store
5703,a15faf55395d2eb26441175d360c6646,1,eu estou com medido de devolução do produto e...,I have the product return measure waiting for ...
5704,bcc07c3639d84c50bb1786b8bcc66116,5,super recomendo produto excelente qualidade,super recommend excellent product quality
5705,7e3154615c510971dc93f2d63397b3db,5,ótimo bem satisfeitaobrigada,great well satisfiedthanks

In [11]:
#save converted reviews into a excel file

nw_df.to_excel("020.xlsx")